function xReturn = bget(obj,string)
%bget(obj,string)
%
%     Input:
%       string = (string)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   string, ...
   };
names = { ...
   'string', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'bget', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#bget', ...
    soapMessage);
xReturn = parseSoapResponse(response);
