function xReturn = binfo(obj,db)
%binfo(obj,db)
%
%     Input:
%       db = (string)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   db, ...
   };
names = { ...
   'db', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'binfo', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#binfo', ...
    soapMessage);
xReturn = parseSoapResponse(response);
