function xReturn = color_pathway_by_objects(obj,pathway_id,object_id_list,fg_color_list,bg_color_list)
%color_pathway_by_objects(obj,pathway_id,object_id_list,fg_color_list,bg_color_list)
%
%     Input:
%       pathway_id = (string)
%       object_id_list{:} = (string)
%       fg_color_list{:} = (string)
%       bg_color_list{:} = (string)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   pathway_id, ...
   object_id_list, ...
   fg_color_list, ...
   bg_color_list, ...
   };
names = { ...
   'pathway_id', ...
   'object_id_list', ...
   'fg_color_list', ...
   'bg_color_list', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string[]', ...
   '{http://www.w3.org/2001/XMLSchema}string[]', ...
   '{http://www.w3.org/2001/XMLSchema}string[]', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'color_pathway_by_objects', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#color_pathway_by_objects', ...
    soapMessage);
xReturn = parseSoapResponse(response);
