function xReturn = convert_mol_to_kcf(obj,mol_text)
%convert_mol_to_kcf(obj,mol_text)
%
%     Input:
%       mol_text = (string)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   mol_text, ...
   };
names = { ...
   'mol_text', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'convert_mol_to_kcf', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#convert_mol_to_kcf', ...
    soapMessage);
xReturn = parseSoapResponse(response);
