function xReturn = get_linkdb_between_databases(obj,from_db,to_db,offset,limit)
%get_linkdb_between_databases(obj,from_db,to_db,offset,limit)
%
%     Input:
%       from_db = (string)
%       to_db = (string)
%       offset = (int)
%       limit = (int)
%   
%     Output:
%       return{:} = (LinkDBRelation)

% Build up the argument lists.
values = { ...
   from_db, ...
   to_db, ...
   offset, ...
   limit, ...
   };
names = { ...
   'from_db', ...
   'to_db', ...
   'offset', ...
   'limit', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_linkdb_between_databases', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_linkdb_between_databases', ...
    soapMessage);
xReturn = parseSoapResponse(response);
