function xReturn = get_number_of_genes_by_organism(obj,abbr)
%get_number_of_genes_by_organism(obj,abbr)
%
%     Input:
%       abbr = (string)
%   
%     Output:
%       return = (int)

% Build up the argument lists.
values = { ...
   abbr, ...
   };
names = { ...
   'abbr', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_number_of_genes_by_organism', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_number_of_genes_by_organism', ...
    soapMessage);
xReturn = parseSoapResponse(response);
