function xReturn = get_pathways_by_kos(obj,ko_id_list,org)
%get_pathways_by_kos(obj,ko_id_list,org)
%
%     Input:
%       ko_id_list{:} = (string)
%       org = (string)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   ko_id_list, ...
   org, ...
   };
names = { ...
   'ko_id_list', ...
   'org', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string[]', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_pathways_by_kos', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_pathways_by_kos', ...
    soapMessage);
xReturn = parseSoapResponse(response);
