function xReturn = get_genes_by_organism(obj,org,offset,limit)
%get_genes_by_organism(obj,org,offset,limit)
%
%     Input:
%       org = (string)
%       offset = (int)
%       limit = (int)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   org, ...
   offset, ...
   limit, ...
   };
names = { ...
   'org', ...
   'offset', ...
   'limit', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_genes_by_organism', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_genes_by_organism', ...
    soapMessage);
xReturn = parseSoapResponse(response);
