function xReturn = get_html_of_colored_pathway_by_elements(obj,pathway_id,element_list,fg_color_list,bg_color_list)
%get_html_of_colored_pathway_by_elements(obj,pathway_id,element_list,fg_color_list,bg_color_list)
%
%     Input:
%       pathway_id = (string)
%       element_list{:} = (int)
%       fg_color_list{:} = (string)
%       bg_color_list{:} = (string)
%   
%     Output:
%       return = (string)

% Build up the argument lists.
values = { ...
   pathway_id, ...
   element_list, ...
   fg_color_list, ...
   bg_color_list, ...
   };
names = { ...
   'pathway_id', ...
   'element_list', ...
   'fg_color_list', ...
   'bg_color_list', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int[]', ...
   '{http://www.w3.org/2001/XMLSchema}string[]', ...
   '{http://www.w3.org/2001/XMLSchema}string[]', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_html_of_colored_pathway_by_elements', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_html_of_colored_pathway_by_elements', ...
    soapMessage);
xReturn = parseSoapResponse(response);
