function xReturn = get_genes_by_ko(obj,ko_id,org)
%get_genes_by_ko(obj,ko_id,org)
%
%     Input:
%       ko_id = (string)
%       org = (string)
%   
%     Output:
%       return{:} = (Definition)

% Build up the argument lists.
values = { ...
   ko_id, ...
   org, ...
   };
names = { ...
   'ko_id', ...
   'org', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_genes_by_ko', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_genes_by_ko', ...
    soapMessage);
xReturn = parseSoapResponse(response);
