function xReturn = get_reactions_by_compound(obj,compound_id)
%get_reactions_by_compound(obj,compound_id)
%
%     Input:
%       compound_id = (string)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   compound_id, ...
   };
names = { ...
   'compound_id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_reactions_by_compound', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_reactions_by_compound', ...
    soapMessage);
xReturn = parseSoapResponse(response);
