function xReturn = get_ko_by_gene(obj,genes_id)
%get_ko_by_gene(obj,genes_id)
%
%     Input:
%       genes_id = (string)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   genes_id, ...
   };
names = { ...
   'genes_id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_ko_by_gene', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_ko_by_gene', ...
    soapMessage);
xReturn = parseSoapResponse(response);
