function xReturn = get_linkdb_by_entry(obj,entry_id,db,offset,limit)
%get_linkdb_by_entry(obj,entry_id,db,offset,limit)
%
%     Input:
%       entry_id = (string)
%       db = (string)
%       offset = (int)
%       limit = (int)
%   
%     Output:
%       return{:} = (LinkDBRelation)

% Build up the argument lists.
values = { ...
   entry_id, ...
   db, ...
   offset, ...
   limit, ...
   };
names = { ...
   'entry_id', ...
   'db', ...
   'offset', ...
   'limit', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   '{http://www.w3.org/2001/XMLSchema}int', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_linkdb_by_entry', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_linkdb_by_entry', ...
    soapMessage);
xReturn = parseSoapResponse(response);
