function xReturn = get_reactions_by_glycan(obj,glycan_id)
%get_reactions_by_glycan(obj,glycan_id)
%
%     Input:
%       glycan_id = (string)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   glycan_id, ...
   };
names = { ...
   'glycan_id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'get_reactions_by_glycan', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#get_reactions_by_glycan', ...
    soapMessage);
xReturn = parseSoapResponse(response);
