function xReturn = list_pathways(obj,org)
%list_pathways(obj,org)
%
%     Input:
%       org = (string)
%   
%     Output:
%       return{:} = (Definition)

% Build up the argument lists.
values = { ...
   org, ...
   };
names = { ...
   'org', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'list_pathways', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#list_pathways', ...
    soapMessage);
xReturn = parseSoapResponse(response);
