function xReturn = list_ko_classes(obj,class_id)
%list_ko_classes(obj,class_id)
%
%     Input:
%       class_id = (string)
%   
%     Output:
%       return{:} = (Definition)

% Build up the argument lists.
values = { ...
   class_id, ...
   };
names = { ...
   'class_id', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'list_ko_classes', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#list_ko_classes', ...
    soapMessage);
xReturn = parseSoapResponse(response);
