function xReturn = search_drugs_by_name(obj,name)
%search_drugs_by_name(obj,name)
%
%     Input:
%       name = (string)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   name, ...
   };
names = { ...
   'name', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}string', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'search_drugs_by_name', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#search_drugs_by_name', ...
    soapMessage);
xReturn = parseSoapResponse(response);
