function xReturn = search_drugs_by_mass(obj,mass,range)
%search_drugs_by_mass(obj,mass,range)
%
%     Input:
%       mass = (float)
%       range = (float)
%   
%     Output:
%       return{:} = (string)

% Build up the argument lists.
values = { ...
   mass, ...
   range, ...
   };
names = { ...
   'mass', ...
   'range', ...
   };
types = { ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   '{http://www.w3.org/2001/XMLSchema}float', ...
   };

% Create the message, make the call, and convert the response into a variable.
soapMessage = createSoapMessage( ...
    'SOAP/KEGG', ...
    'search_drugs_by_mass', ...
    values,names,types,'rpc');
response = callSoapService( ...
    obj.endpoint, ...
    'SOAP/KEGG#search_drugs_by_mass', ...
    soapMessage);
xReturn = parseSoapResponse(response);
